modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="sweetnotsavourymod"
version="${file.jarVersion}"
displayName="Sweet Not Savoury Mod"
logoFile="tutorialmod.png"
credits="Sweet Not Savoury Mod by Charlotte"
description='''
Mod by Charlotte.
'''

[[dependencies.sweetnotsavourymod]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sweetnotsavourymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sweetnotsavourymod]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.37,)"
    ordering="BEFORE"
    side="BOTH"
